/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import type {
  BaseQuery,
  HttpResultListSystemDictDataDto,
  HttpResultPageSystemDictDataDto,
  HttpResultString,
  HttpResultSystemDictDataDto
} from '../models';
import { STABaseService, STAHttpOptions } from '../_base.service';

/**
 * 数据字典管理
 */
@Injectable({ providedIn: 'root' })
export class SystemDictDataService extends STABaseService {
  /**
   * 分页查询接口 - 分页查询接口
   *
   * @request POST:/dict-data/page-all
   */
  pageSystemDictDataAll(req: BaseQuery, options?: STAHttpOptions): Observable<HttpResultPageSystemDictDataDto> {
    return this.request('POST', `/dict-data/page-all`, {
      body: req,
      ...options
    });
  }

  /**
   * 通过id查询接口 - 通过id查询接口
   *
   * @request GET:/dict-data/{id}
   */
  findSystemDictDataDtoById(id: number, options?: STAHttpOptions): Observable<HttpResultSystemDictDataDto> {
    return this.request('GET', `/dict-data/${id}`, {
      ...options
    });
  }

  /**
   * 通过id逻辑删除接口 - 通过id逻辑删除接口
   *
   * @request DELETE:/dict-data/{id}
   */
  deleteSystemDictDataById(id: number, options?: STAHttpOptions): Observable<HttpResultString> {
    return this.request('DELETE', `/dict-data/${id}`, {
      ...options
    });
  }

  /**
   * 全量查询接口 - 全量查询接口
   *
   * @request GET:/dict-data/find-all
   */
  findSystemDictDataAll(options?: STAHttpOptions): Observable<HttpResultListSystemDictDataDto> {
    return this.request('GET', `/dict-data/find-all`, {
      ...options
    });
  }
}
