/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import type {
  BaseQuery,
  HttpResultListRegionDTO,
  HttpResultPageRegionDTO,
  HttpResultRegionDTO,
  HttpResultString,
  RegionDTO
} from '../models';
import { STABaseService, STAHttpOptions } from '../_base.service';

@Injectable({ providedIn: 'root' })
export class RegionResourceService extends STABaseService {
  /**
   * 修改 - 修改
   *
   * @request PUT:/api/region
   */
  update1(req: RegionDTO, options?: STAHttpOptions): Observable<HttpResultRegionDTO> {
    return this.request('PUT', `/api/region`, {
      body: req,
      ...options
    });
  }

  /**
   * 添加 - 添加
   *
   * @request POST:/api/region
   */
  save1(req: RegionDTO, options?: STAHttpOptions): Observable<HttpResultRegionDTO> {
    return this.request('POST', `/api/region`, {
      body: req,
      ...options
    });
  }

  /**
   * 分页查询接口 - 分页查询接口
   *
   * @request POST:/api/region/page-all
   */
  pageAll1(req: BaseQuery, options?: STAHttpOptions): Observable<HttpResultPageRegionDTO> {
    return this.request('POST', `/api/region/page-all`, {
      body: req,
      ...options
    });
  }

  /**
   * 通过id查询接口 - 通过id查询接口
   *
   * @request GET:/api/region/{id}
   */
  findDtoById1(id: number, options?: STAHttpOptions): Observable<HttpResultRegionDTO> {
    return this.request('GET', `/api/region/${id}`, {
      ...options
    });
  }

  /**
   * 通过id逻辑删除接口 - 通过id逻辑删除接口
   *
   * @request DELETE:/api/region/{id}
   */
  deleteById1(id: number, options?: STAHttpOptions): Observable<HttpResultString> {
    return this.request('DELETE', `/api/region/${id}`, {
      ...options
    });
  }

  /**
   * 全量查询接口 - 全量查询接口
   *
   * @request GET:/api/region/find-all
   */
  findAll1(options?: STAHttpOptions): Observable<HttpResultListRegionDTO> {
    return this.request('GET', `/api/region/find-all`, {
      ...options
    });
  }
}
