/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import type {
  BaseQuery,
  DepartmentDTO,
  HttpResultDepartmentDTO,
  HttpResultListDepartmentDTO,
  HttpResultPageDepartmentDTO,
  HttpResultString
} from '../models';
import { STABaseService, STAHttpOptions } from '../_base.service';

@Injectable({ providedIn: 'root' })
export class DepartmentResourceService extends STABaseService {
  /**
   * 修改 - 修改
   *
   * @request PUT:/api/department
   */
  update6(req: DepartmentDTO, options?: STAHttpOptions): Observable<HttpResultDepartmentDTO> {
    return this.request('PUT', `/api/department`, {
      body: req,
      ...options
    });
  }

  /**
   * 添加 - 添加
   *
   * @request POST:/api/department
   */
  save6(req: DepartmentDTO, options?: STAHttpOptions): Observable<HttpResultDepartmentDTO> {
    return this.request('POST', `/api/department`, {
      body: req,
      ...options
    });
  }

  /**
   * 分页查询接口 - 分页查询接口
   *
   * @request POST:/api/department/page-all
   */
  pageAll6(req: BaseQuery, options?: STAHttpOptions): Observable<HttpResultPageDepartmentDTO> {
    return this.request('POST', `/api/department/page-all`, {
      body: req,
      ...options
    });
  }

  /**
   * 通过id查询接口 - 通过id查询接口
   *
   * @request GET:/api/department/{id}
   */
  findDtoById6(id: number, options?: STAHttpOptions): Observable<HttpResultDepartmentDTO> {
    return this.request('GET', `/api/department/${id}`, {
      ...options
    });
  }

  /**
   * 通过id逻辑删除接口 - 通过id逻辑删除接口
   *
   * @request DELETE:/api/department/{id}
   */
  deleteById6(id: number, options?: STAHttpOptions): Observable<HttpResultString> {
    return this.request('DELETE', `/api/department/${id}`, {
      ...options
    });
  }

  /**
   * 全量查询接口 - 全量查询接口
   *
   * @request GET:/api/department/find-all
   */
  findAll6(options?: STAHttpOptions): Observable<HttpResultListDepartmentDTO> {
    return this.request('GET', `/api/department/find-all`, {
      ...options
    });
  }
}
