/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import type { BaseQuery, HttpResultJobDTO, HttpResultListJobDTO, HttpResultPageJobDTO, HttpResultString, JobDTO } from '../models';
import { STABaseService, STAHttpOptions } from '../_base.service';

@Injectable({ providedIn: 'root' })
export class JobResourceService extends STABaseService {
  /**
   * 修改 - 修改
   *
   * @request PUT:/api/job
   */
  update3(req: JobDTO, options?: STAHttpOptions): Observable<HttpResultJobDTO> {
    return this.request('PUT', `/api/job`, {
      body: req,
      ...options
    });
  }

  /**
   * 添加 - 添加
   *
   * @request POST:/api/job
   */
  save3(req: JobDTO, options?: STAHttpOptions): Observable<HttpResultJobDTO> {
    return this.request('POST', `/api/job`, {
      body: req,
      ...options
    });
  }

  /**
   * 分页查询接口 - 分页查询接口
   *
   * @request POST:/api/job/page-all
   */
  pageAll4(req: BaseQuery, options?: STAHttpOptions): Observable<HttpResultPageJobDTO> {
    return this.request('POST', `/api/job/page-all`, {
      body: req,
      ...options
    });
  }

  /**
   * 通过id查询接口 - 通过id查询接口
   *
   * @request GET:/api/job/{id}
   */
  findDtoById4(id: number, options?: STAHttpOptions): Observable<HttpResultJobDTO> {
    return this.request('GET', `/api/job/${id}`, {
      ...options
    });
  }

  /**
   * 通过id逻辑删除接口 - 通过id逻辑删除接口
   *
   * @request DELETE:/api/job/{id}
   */
  deleteById4(id: number, options?: STAHttpOptions): Observable<HttpResultString> {
    return this.request('DELETE', `/api/job/${id}`, {
      ...options
    });
  }

  /**
   * 全量查询接口 - 全量查询接口
   *
   * @request GET:/api/job/find-all
   */
  findAll4(options?: STAHttpOptions): Observable<HttpResultListJobDTO> {
    return this.request('GET', `/api/job/find-all`, {
      ...options
    });
  }
}
