/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import type {
  BaseQuery,
  HttpResultListSystemDictTypeDto,
  HttpResultPageSystemDictTypeDto,
  HttpResultString,
  HttpResultSystemDictTypeDto,
  HttpResultUser,
  SystemDictTypeDto
} from '../models';
import { STABaseService, STAHttpOptions } from '../_base.service';

/**
 * 数据字典类型管理
 */
@Injectable({ providedIn: 'root' })
export class SystemDictTypeService extends STABaseService {
  /**
   * 修改字典类型接口
   *
   * @request PUT:/dict-type
   */
  updateSystemDictType(req: SystemDictTypeDto, options?: STAHttpOptions): Observable<HttpResultSystemDictTypeDto> {
    return this.request('PUT', `/dict-type`, {
      body: req,
      ...options
    });
  }

  /**
   * 添加字典类型接口
   *
   * @request POST:/dict-type
   */
  addSystemDictType(req: SystemDictTypeDto, options?: STAHttpOptions): Observable<HttpResultSystemDictTypeDto> {
    return this.request('POST', `/dict-type`, {
      body: req,
      ...options
    });
  }

  /**
   * 分页查询接口 - 分页查询接口
   *
   * @request POST:/dict-type/page-all
   */
  pageSystemDictTypeAll(req: BaseQuery, options?: STAHttpOptions): Observable<HttpResultPageSystemDictTypeDto> {
    return this.request('POST', `/dict-type/page-all`, {
      body: req,
      ...options
    });
  }

  /**
   * 数据脱敏测试接口
   *
   * @request POST:/dict-type/desensitization
   */
  desensitization(options?: STAHttpOptions): Observable<HttpResultUser> {
    return this.request('POST', `/dict-type/desensitization`, {
      ...options
    });
  }

  /**
   * 通过id查询接口 - 通过id查询接口
   *
   * @request GET:/dict-type/{id}
   */
  findSystemDictTypeDtoById(id: number, options?: STAHttpOptions): Observable<HttpResultSystemDictTypeDto> {
    return this.request('GET', `/dict-type/${id}`, {
      ...options
    });
  }

  /**
   * 删除字典类型接口
   *
   * @request DELETE:/dict-type/{id}
   */
  deleteSystemDictTypeById(id: number, options?: STAHttpOptions): Observable<HttpResultString> {
    return this.request('DELETE', `/dict-type/${id}`, {
      ...options
    });
  }

  /**
   * 全量查询接口 - 全量查询接口
   *
   * @request GET:/dict-type/find-all
   */
  findSystemDictTypeAll(options?: STAHttpOptions): Observable<HttpResultListSystemDictTypeDto> {
    return this.request('GET', `/dict-type/find-all`, {
      ...options
    });
  }
}
