/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

export * from './models';
export * from './_base.service';
export * from './systemDictType/index';
export * from './systemDictData/index';