/* eslint-disable */

/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

export interface SystemDictTypeDto {
  /** @format int64 */
  id?: number;
  name?: string;
  type?: string;

  /** @format int32 */
  status?: number;
}

export interface HttpResultSystemDictTypeDto {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: SystemDictTypeDto;
}

export interface BaseQuery {
  /**
   * 分页大小
   * @format int32
   */
  pageSize?: number;

  /**
   * 页数
   * @format int32
   */
  pageNo?: number;
}

export interface HttpResultPageSystemDictTypeDto {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: PageSystemDictTypeDto;
}

export interface PageSystemDictTypeDto {
  /** @format int32 */
  totalPages?: number;

  /** @format int64 */
  totalElements?: number;
  last?: boolean;
  first?: boolean;
  pageable?: PageableObject;

  /** @format int32 */
  numberOfElements?: number;

  /** @format int32 */
  size?: number;
  content?: SystemDictTypeDto[];

  /** @format int32 */
  number?: number;
  sort?: Sort;
  empty?: boolean;
}

export interface PageableObject {
  paged?: boolean;
  unpaged?: boolean;

  /** @format int32 */
  pageNumber?: number;

  /** @format int32 */
  pageSize?: number;

  /** @format int64 */
  offset?: number;
  sort?: Sort;
}

export interface Sort {
  sorted?: boolean;
  unsorted?: boolean;
  empty?: boolean;
}

export interface HttpResultUser {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: User;
}

export interface User {
  name?: string;
  idCard?: string;
  mobile?: string;
  id?: string;
  address?: string;
}

export interface HttpResultPageSystemDictDataDto {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: PageSystemDictDataDto;
}

export interface PageSystemDictDataDto {
  /** @format int32 */
  totalPages?: number;

  /** @format int64 */
  totalElements?: number;
  last?: boolean;
  first?: boolean;
  pageable?: PageableObject;

  /** @format int32 */
  numberOfElements?: number;

  /** @format int32 */
  size?: number;
  content?: SystemDictDataDto[];

  /** @format int32 */
  number?: number;
  sort?: Sort;
  empty?: boolean;
}

export interface SystemDictDataDto {
  /** @format int64 */
  id?: number;
  systemDictType?: SystemDictTypeDto;
  label?: string;
  value?: string;

  /** @format int64 */
  dictSort?: number;

  /** @format int32 */
  status?: number;
}

export interface HttpResultListSystemDictTypeDto {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: SystemDictTypeDto[];
}

export interface HttpResultSystemDictDataDto {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: SystemDictDataDto;
}

export interface HttpResultListSystemDictDataDto {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: SystemDictDataDto[];
}

export interface HttpResultString {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: string;
}
