/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import type {
  BaseQuery,
  HttpResultJobHistoryDTO,
  HttpResultListJobHistoryDTO,
  HttpResultPageJobHistoryDTO,
  HttpResultString,
  JobHistoryDTO
} from '../models';
import { STABaseService, STAHttpOptions } from '../_base.service';

@Injectable({ providedIn: 'root' })
export class JobHistoryResourceService extends STABaseService {
  /**
   * 修改 - 修改
   *
   * @request PUT:/api/jobHistory
   */
  update4(req: JobHistoryDTO, options?: STAHttpOptions): Observable<HttpResultJobHistoryDTO> {
    return this.request('PUT', `/api/jobHistory`, {
      body: req,
      ...options
    });
  }

  /**
   * 添加 - 添加
   *
   * @request POST:/api/jobHistory
   */
  save4(req: JobHistoryDTO, options?: STAHttpOptions): Observable<HttpResultJobHistoryDTO> {
    return this.request('POST', `/api/jobHistory`, {
      body: req,
      ...options
    });
  }

  /**
   * 分页查询接口 - 分页查询接口
   *
   * @request POST:/api/jobHistory/page-all
   */
  pageAll3(req: BaseQuery, options?: STAHttpOptions): Observable<HttpResultPageJobHistoryDTO> {
    return this.request('POST', `/api/jobHistory/page-all`, {
      body: req,
      ...options
    });
  }

  /**
   * 通过id查询接口 - 通过id查询接口
   *
   * @request GET:/api/jobHistory/{id}
   */
  findDtoById3(id: number, options?: STAHttpOptions): Observable<HttpResultJobHistoryDTO> {
    return this.request('GET', `/api/jobHistory/${id}`, {
      ...options
    });
  }

  /**
   * 通过id逻辑删除接口 - 通过id逻辑删除接口
   *
   * @request DELETE:/api/jobHistory/{id}
   */
  deleteById3(id: number, options?: STAHttpOptions): Observable<HttpResultString> {
    return this.request('DELETE', `/api/jobHistory/${id}`, {
      ...options
    });
  }

  /**
   * 全量查询接口 - 全量查询接口
   *
   * @request GET:/api/jobHistory/find-all
   */
  findAll3(options?: STAHttpOptions): Observable<HttpResultListJobHistoryDTO> {
    return this.request('GET', `/api/jobHistory/find-all`, {
      ...options
    });
  }
}
