/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

export * from './models';
export * from './_base.service';
export * from './taskResource/index';
export * from './regionResource/index';
export * from './locationResource/index';
export * from './jobResource/index';
export * from './jobHistoryResource/index';
export * from './employeeResource/index';
export * from './departmentResource/index';
export * from './countryResource/index';