/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

/**
* Task entity.
@author The JHipster team.
*/
export interface TaskDTO {
  /** @format int64 */
  id?: number;
  title?: string;
  description?: string;
}

export interface HttpResultTaskDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;

  /**
   * Task entity.
   * @author The JHipster team.
   */
  data?: TaskDTO;
}

/**
 * 区域
 */
export interface RegionDTO {
  /** @format int64 */
  id?: number;

  /** 区域名称 */
  regionName?: string;

  /** 区域code */
  code?: string;
}

export interface HttpResultRegionDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;

  /** 区域 */
  data?: RegionDTO;
}

/**
 * 国家
 */
export interface CountryDTO {
  /** @format int64 */
  id?: number;

  /** 国家名称 */
  countryName?: string;

  /** 区域 */
  region?: RegionDTO;
}

/**
 * 地址
 */
export interface LocationDTO {
  /** @format int64 */
  id?: number;
  streetAddress?: string;
  postalCode?: string;
  city?: string;
  stateProvince?: string;

  /** 国家 */
  country?: CountryDTO;
}

export interface HttpResultLocationDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;

  /** 地址 */
  data?: LocationDTO;
}

export interface DepartmentDTO {
  /** @format int64 */
  id?: number;
  departmentName: string;

  /** 地址 */
  location?: LocationDTO;
}

/**
 * The Employee entity.
 */
export interface EmployeeDTO {
  /** @format int64 */
  id?: number;

  /** The firstname attribute. */
  firstName?: string;
  lastName?: string;
  email?: string;
  phoneNumber?: string;

  /** @format date-time */
  hireDate?: string;

  /** @format int64 */
  salary?: number;

  /** @format int64 */
  commissionPct?: number;

  /** The Employee entity. */
  manager?: EmployeeDTO;
  department?: DepartmentDTO;
}

export interface JobDTO {
  /** @format int64 */
  id?: number;
  jobTitle?: string;

  /** @format int64 */
  minSalary?: number;

  /** @format int64 */
  maxSalary?: number;
  tasks?: TaskDTO[];

  /** The Employee entity. */
  employee?: EmployeeDTO;
}

export interface HttpResultJobDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: JobDTO;
}

export interface JobHistoryDTO {
  /** @format int64 */
  id?: number;

  /** @format date-time */
  startDate?: string;

  /** @format date-time */
  endDate?: string;
  language?: 'FRENCH' | 'ENGLISH' | 'SPANISH';
  job?: JobDTO;
  department?: DepartmentDTO;

  /** The Employee entity. */
  employee?: EmployeeDTO;
}

export interface HttpResultJobHistoryDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: JobHistoryDTO;
}

export interface HttpResultEmployeeDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;

  /** The Employee entity. */
  data?: EmployeeDTO;
}

export interface HttpResultDepartmentDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: DepartmentDTO;
}

export interface HttpResultCountryDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;

  /** 国家 */
  data?: CountryDTO;
}

export interface BaseQuery {
  /**
   * 分页大小
   * @format int32
   */
  pageSize?: number;

  /**
   * 页数
   * @format int32
   */
  pageNo?: number;
}

export interface HttpResultPageTaskDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: PageTaskDTO;
}

export interface PageTaskDTO {
  /** @format int32 */
  totalPages?: number;

  /** @format int64 */
  totalElements?: number;
  pageable?: PageableObject;

  /** @format int32 */
  numberOfElements?: number;
  last?: boolean;
  first?: boolean;

  /** @format int32 */
  size?: number;
  content?: TaskDTO[];

  /** @format int32 */
  number?: number;
  sort?: Sort;
  empty?: boolean;
}

export interface PageableObject {
  unpaged?: boolean;

  /** @format int32 */
  pageNumber?: number;

  /** @format int32 */
  pageSize?: number;
  paged?: boolean;

  /** @format int64 */
  offset?: number;
  sort?: Sort;
}

export interface Sort {
  unsorted?: boolean;
  sorted?: boolean;
  empty?: boolean;
}

export interface HttpResultPageRegionDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: PageRegionDTO;
}

export interface PageRegionDTO {
  /** @format int32 */
  totalPages?: number;

  /** @format int64 */
  totalElements?: number;
  pageable?: PageableObject;

  /** @format int32 */
  numberOfElements?: number;
  last?: boolean;
  first?: boolean;

  /** @format int32 */
  size?: number;
  content?: RegionDTO[];

  /** @format int32 */
  number?: number;
  sort?: Sort;
  empty?: boolean;
}

export interface HttpResultPageLocationDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: PageLocationDTO;
}

export interface PageLocationDTO {
  /** @format int32 */
  totalPages?: number;

  /** @format int64 */
  totalElements?: number;
  pageable?: PageableObject;

  /** @format int32 */
  numberOfElements?: number;
  last?: boolean;
  first?: boolean;

  /** @format int32 */
  size?: number;
  content?: LocationDTO[];

  /** @format int32 */
  number?: number;
  sort?: Sort;
  empty?: boolean;
}

export interface HttpResultPageJobHistoryDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: PageJobHistoryDTO;
}

export interface PageJobHistoryDTO {
  /** @format int32 */
  totalPages?: number;

  /** @format int64 */
  totalElements?: number;
  pageable?: PageableObject;

  /** @format int32 */
  numberOfElements?: number;
  last?: boolean;
  first?: boolean;

  /** @format int32 */
  size?: number;
  content?: JobHistoryDTO[];

  /** @format int32 */
  number?: number;
  sort?: Sort;
  empty?: boolean;
}

export interface HttpResultPageJobDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: PageJobDTO;
}

export interface PageJobDTO {
  /** @format int32 */
  totalPages?: number;

  /** @format int64 */
  totalElements?: number;
  pageable?: PageableObject;

  /** @format int32 */
  numberOfElements?: number;
  last?: boolean;
  first?: boolean;

  /** @format int32 */
  size?: number;
  content?: JobDTO[];

  /** @format int32 */
  number?: number;
  sort?: Sort;
  empty?: boolean;
}

export interface HttpResultPageEmployeeDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: PageEmployeeDTO;
}

export interface PageEmployeeDTO {
  /** @format int32 */
  totalPages?: number;

  /** @format int64 */
  totalElements?: number;
  pageable?: PageableObject;

  /** @format int32 */
  numberOfElements?: number;
  last?: boolean;
  first?: boolean;

  /** @format int32 */
  size?: number;
  content?: EmployeeDTO[];

  /** @format int32 */
  number?: number;
  sort?: Sort;
  empty?: boolean;
}

export interface HttpResultPageDepartmentDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: PageDepartmentDTO;
}

export interface PageDepartmentDTO {
  /** @format int32 */
  totalPages?: number;

  /** @format int64 */
  totalElements?: number;
  pageable?: PageableObject;

  /** @format int32 */
  numberOfElements?: number;
  last?: boolean;
  first?: boolean;

  /** @format int32 */
  size?: number;
  content?: DepartmentDTO[];

  /** @format int32 */
  number?: number;
  sort?: Sort;
  empty?: boolean;
}

export interface HttpResultPageCountryDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: PageCountryDTO;
}

export interface PageCountryDTO {
  /** @format int32 */
  totalPages?: number;

  /** @format int64 */
  totalElements?: number;
  pageable?: PageableObject;

  /** @format int32 */
  numberOfElements?: number;
  last?: boolean;
  first?: boolean;

  /** @format int32 */
  size?: number;
  content?: CountryDTO[];

  /** @format int32 */
  number?: number;
  sort?: Sort;
  empty?: boolean;
}

export interface HttpResultListTaskDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: TaskDTO[];
}

export interface HttpResultListRegionDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: RegionDTO[];
}

export interface HttpResultListLocationDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: LocationDTO[];
}

export interface HttpResultListJobHistoryDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: JobHistoryDTO[];
}

export interface HttpResultListJobDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: JobDTO[];
}

export interface HttpResultListEmployeeDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: EmployeeDTO[];
}

export interface HttpResultListDepartmentDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: DepartmentDTO[];
}

export interface HttpResultListCountryDTO {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: CountryDTO[];
}

export interface HttpResultString {
  /** @format int32 */
  code?: number;
  success?: boolean;
  message?: string;
  data?: string;
}
