/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import type {
  BaseQuery,
  CountryDTO,
  HttpResultCountryDTO,
  HttpResultListCountryDTO,
  HttpResultPageCountryDTO,
  HttpResultString
} from '../models';
import { STABaseService, STAHttpOptions } from '../_base.service';

@Injectable({ providedIn: 'root' })
export class CountryResourceService extends STABaseService {
  /**
   * 修改 - 修改
   *
   * @request PUT:/api/country
   */
  update7(req: CountryDTO, options?: STAHttpOptions): Observable<HttpResultCountryDTO> {
    return this.request('PUT', `/api/country`, {
      body: req,
      ...options
    });
  }

  /**
   * 添加 - 添加
   *
   * @request POST:/api/country
   */
  save7(req: CountryDTO, options?: STAHttpOptions): Observable<HttpResultCountryDTO> {
    return this.request('POST', `/api/country`, {
      body: req,
      ...options
    });
  }

  /**
   * 分页查询接口 - 分页查询接口
   *
   * @request POST:/api/country/page-all
   */
  pageAll7(req: BaseQuery, options?: STAHttpOptions): Observable<HttpResultPageCountryDTO> {
    return this.request('POST', `/api/country/page-all`, {
      body: req,
      ...options
    });
  }

  /**
   * 通过id查询接口 - 通过id查询接口
   *
   * @request GET:/api/country/{id}
   */
  findDtoById7(id: number, options?: STAHttpOptions): Observable<HttpResultCountryDTO> {
    return this.request('GET', `/api/country/${id}`, {
      ...options
    });
  }

  /**
   * 通过id逻辑删除接口 - 通过id逻辑删除接口
   *
   * @request DELETE:/api/country/{id}
   */
  deleteById7(id: number, options?: STAHttpOptions): Observable<HttpResultString> {
    return this.request('DELETE', `/api/country/${id}`, {
      ...options
    });
  }

  /**
   * 全量查询接口 - 全量查询接口
   *
   * @request GET:/api/country/find-all
   */
  findAll7(options?: STAHttpOptions): Observable<HttpResultListCountryDTO> {
    return this.request('GET', `/api/country/find-all`, {
      ...options
    });
  }
}
