/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import type {
  BaseQuery,
  EmployeeDTO,
  HttpResultEmployeeDTO,
  HttpResultListEmployeeDTO,
  HttpResultPageEmployeeDTO,
  HttpResultString
} from '../models';
import { STABaseService, STAHttpOptions } from '../_base.service';

@Injectable({ providedIn: 'root' })
export class EmployeeResourceService extends STABaseService {
  /**
   * 修改 - 修改
   *
   * @request PUT:/api/employee
   */
  update5(req: EmployeeDTO, options?: STAHttpOptions): Observable<HttpResultEmployeeDTO> {
    return this.request('PUT', `/api/employee`, {
      body: req,
      ...options
    });
  }

  /**
   * 添加 - 添加
   *
   * @request POST:/api/employee
   */
  save5(req: EmployeeDTO, options?: STAHttpOptions): Observable<HttpResultEmployeeDTO> {
    return this.request('POST', `/api/employee`, {
      body: req,
      ...options
    });
  }

  /**
   * 分页查询接口 - 分页查询接口
   *
   * @request POST:/api/employee/page-all
   */
  pageAll5(req: BaseQuery, options?: STAHttpOptions): Observable<HttpResultPageEmployeeDTO> {
    return this.request('POST', `/api/employee/page-all`, {
      body: req,
      ...options
    });
  }

  /**
   * 通过id查询接口 - 通过id查询接口
   *
   * @request GET:/api/employee/{id}
   */
  findDtoById5(id: number, options?: STAHttpOptions): Observable<HttpResultEmployeeDTO> {
    return this.request('GET', `/api/employee/${id}`, {
      ...options
    });
  }

  /**
   * 通过id逻辑删除接口 - 通过id逻辑删除接口
   *
   * @request DELETE:/api/employee/{id}
   */
  deleteById5(id: number, options?: STAHttpOptions): Observable<HttpResultString> {
    return this.request('DELETE', `/api/employee/${id}`, {
      ...options
    });
  }

  /**
   * 全量查询接口 - 全量查询接口
   *
   * @request GET:/api/employee/find-all
   */
  findAll5(options?: STAHttpOptions): Observable<HttpResultListEmployeeDTO> {
    return this.request('GET', `/api/employee/find-all`, {
      ...options
    });
  }
}
